### ISSUE TITLE
java.lang.ClassNotFoundException: kotlin.text.StringsKt due to missing dependencies

### ISSUE THREAD

**Issue by MixMasterRickyC** [mopub/mopub-unity-sdk#105]
Caused by: java.lang.ClassNotFoundException: kotlin.text.StringsKt due to missing dependency.

#### MoPub SDK Version:
5.11

#### Device model and OS Version:
Google Pixel, Android 10

#### Unity Version:
2018.4.11f1

#### Ad Unit IDs used in reproducing the issue:
4d801540aa6342e98e49118c5169c4c4

#### Steps to reproduce the behavior:

Issue with MoPub 5.11 and Facebook Audience Network (5.6.1.0)

This only started happening after moving to the latest version of MoPub as the version of Audience Network hadn't changed.

The latest version of MoPub requires the Kotlin stdlib which seems to be missing the MoPubDependencies.xml

I've manually added this myself but it would be better if this was included by default.

```
<dependencies>
  <androidPackages>
    <androidPackage spec="androidx.legacy:legacy-support-v4:1.0.0"/>
    <androidPackage spec="androidx.appcompat:appcompat:1.1.0"/>
    <androidPackage spec="org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.61"/>
  </androidPackages>
  <iosPods>
    <iosPod name="MoPub-SDK-Plugin" minTargetSdk="9.0" path="Assets/MoPub/Plugins/iOS"/>
    <iosPod name="mopub-ios-sdk" subspecs="['Core']" minTargetSdk="9.0" version="5.11.0"/>
  </iosPods>
</dependencies>
```

#### Steps Below

Load the placement, as soon as it's finished loading it will crash.
See crash log below.

#### Evidence:

```
--------- beginning of crash
02-11 13:22:04.524 22863 22863 E AndroidRuntime: FATAL EXCEPTION: main
02-11 13:22:04.524 22863 22863 E AndroidRuntime: Process: com.application.name PID: 22863
02-11 13:22:04.524 22863 22863 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/text/StringsKt;
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at com.mopub.mobileads.VideoTrackingEvent$Companion.fromString(VideoTrackingEvent.kt:22)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at com.mopub.mobileads.VastVideoConfig.addVideoTrackers(VastVideoConfig.java:256)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at com.mopub.mobileads.VastVideoInterstitial.onVastVideoConfigurationPrepared(VastVideoInterstitial.java:112)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at com.mopub.mobileads.RewardedVastVideoInterstitial.onVastVideoConfigurationPrepared(RewardedVastVideoInterstitial.java:50)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at com.mopub.mobileads.VastManager.onAggregationComplete(VastManager.java:121)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at com.mopub.mobileads.VastXmlManagerAggregator.onPostExecute(VastXmlManagerAggregator.java:140)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at com.mopub.mobileads.VastXmlManagerAggregator.onPostExecute(VastXmlManagerAggregator.java:50)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at android.os.AsyncTask.finish(AsyncTask.java:755)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at android.os.AsyncTask.access$900(AsyncTask.java:192)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:772)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
02-11 13:22:04.524 22863 22863 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: kotlin.text.StringsKt
02-11 13:22:04.524 22863 22863 E AndroidRuntime: 	... 16 more
```

**Comment by chauduyphanvu** [comment]
@MixMasterRickyC, thanks for letting us know! I confirm I was able to reproduce this crash and have let the rest of the team know. I'll share an update once we have one.

Vu Chau
MoPub Team

**Comment by chauduyphanvu** [comment]
We've addressed this internally and the fix will be deployed in an upcoming SDK version. Stay tuned!

Meanwhile, your fix looks good to us, too.

**Comment by aornelas** [comment]
This issue has been fixed in the latest release: https://github.com/mopub/mopub-unity-sdk/releases/tag/v5.11.1

Thanks for reporting!
