### ISSUE TITLE
Android test project using sample scene is crashing

### ISSUE THREAD

**Issue by apautrot** [mopub/mopub-unity-sdk#26]
Android test project using sample scene is crashing. The is a missing dependency, which does not resolve at runtime, which leads to a crash.

- [x] I am submitting a bug report for existing functionality
- [x] I visited https://developers.mopub.com/ and found no answer
- [x] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [x] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.4.1

#### Device model and OS Version:
HUAWEI CUN-L21
Android 5.1

#### Unity Version:
2018.2.18f1

#### Ad Unit IDs used in reproducing the issue:
b195f8dd8ded45fe847ad89ed1d016da
(adunitid of banner, coming from sample of MoPub SDK)

#### Steps to reproduce the behavior:
- Running the sample scene provided in the SDK.
- Clicking button "Request b195f8dd8d...".

#### Expected behavior:
Expected the test banner to load and show up.

#### Observed behavior:
Application is shutdown.
Logcat details a crash due to a fatal exception.

#### Evidence:
```
I/Unity: requesting banner with AdUnit: b195f8dd8ded45fe847ad89ed1d016da
          
         (Filename: ./Runtime/Export/Debug.bindings.h Line: 43)
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.mycompany.testmopub, PID: 6011
                  java.lang.Error: FATAL EXCEPTION [main]
                  Unity version     : 2018.2.18f1
                  Device model      : HUAWEI HUAWEI CUN-L21
                  Device fingerprint: HUAWEI/CUN-L21/HWCUN-L6735:5.1/HUAWEICUN-L21/C577B122:user/release-keys
                  
                  Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
                      at com.mopub.common.util.DeviceUtils.isPermissionGranted(DeviceUtils.java:258)
                      at com.mopub.mraid.MraidNativeCommandHandler.isStorePictureSupported(MraidNativeCommandHandler.java:141)
                      at com.mopub.mobileads.AdViewController.<init>(AdViewController.java:118)
                      at com.mopub.mobileads.factories.AdViewControllerFactory.internalCreate(AdViewControllerFactory.java:25)
                      at com.mopub.mobileads.factories.AdViewControllerFactory.create(AdViewControllerFactory.java:21)
                      at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:72)
                      at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:58)
                      at com.mopub.unity.MoPubBannerUnityPlugin$1.run(MoPubBannerUnityPlugin.java:58)
                      at com.mopub.unity.MoPubUnityPlugin$9.run(MoPubUnityPlugin.java:450)
                      at android.os.Handler.handleCallback(Handler.java:815)
                      at android.os.Handler.dispatchMessage(Handler.java:104)
                      at android.os.Looper.loop(Looper.java:194)
                      at android.app.ActivityThread.main(ActivityThread.java:5931)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:372)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/com.alexispautrot.testmopub-1/base.apk"],nativeLibraryDirectories=[/data/app/com.alexispautrot.testmopub-1/lib/arm, /vendor/lib, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                      at com.mopub.common.util.DeviceUtils.isPermissionGranted(DeviceUtils.java:258) 
                      at com.mopub.mraid.MraidNativeCommandHandler.isStorePictureSupported(MraidNativeCommandHandler.java:141) 
                      at com.mopub.mobileads.AdViewController.<init>(AdViewController.java:118) 
                      at com.mopub.mobileads.factories.AdViewControllerFactory.internalCreate(AdViewControllerFactory.java:25) 
                      at com.mopub.mobileads.factories.AdViewControllerFactory.create(AdViewControllerFactory.java:21) 
                      at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:72) 
                      at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:58) 
                      at com.mopub.unity.MoPubBannerUnityPlugin$1.run(MoPubBannerUnityPlugin.java:58) 
                      at com.mopub.unity.MoPubUnityPlugin$9.run(MoPubUnityPlugin.java:450) 
                      at android.os.Handler.handleCallback(Handler.java:815) 
                      at android.os.Handler.dispatchMessage(Handler.java:104) 
                      at android.os.Looper.loop(Looper.java:194) 
                      at android.app.ActivityThread.main(ActivityThread.java:5931) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:372) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:987) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782) 
                  	Suppressed: java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat
                      at java.lang.Class.classForName(Native Method)
                      at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                      at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                      		... 18 more
                   Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
W/ActivityManager:   Force finishing activity 1 com.mycompany.testmopub/com.unity3d.player.UnityPlayerActivity
```

Don't hesitate to contact me to get the Unity project in order to reproduce this issue.

**Comment by sdolim** [comment]
There should be an Android v4 Support jar (or aar) in your project somewhere, like in Plugins/Android or Plugins/Android/mopub.  Can you see if there is one or if it is missing?

**Comment by apautrot** [comment]
No there is none.

I resolved the issue by activating "Custom gradle template" option in Unity Player settings (Publishing Settings) and then adding the line "compile 'com.android.support:support-v4:23.0.0'" to it.

I followed the answer given for a similar issue on stackoverflow : https://stackoverflow.com/questions/31733044/cannot-resolve-contextcompat-in-android

**Comment by sdolim** [comment]
OK, great that you are unblocked.  It appears that the support jar is part of our public SDK repo (in the directory unity-sample-app/Assets/Plugins/Android/libs) but is missing from the unitypackage.  Thanks for letting us know!
