### ISSUE TITLE
Android app crashes: Can´t find android.support.v4.content.ContextCompact

### ISSUE THREAD

**Issue by Romaleks360** [mopub/mopub-unity-sdk#29]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat

- [X] I am submitting a bug report for existing functionality
- [X] I visited https://developers.mopub.com/ and found no answer
- [X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.4.1
#### Device model and OS Version:
Android 8
#### Unity Version:
2018.3.2f1
#### Ad Unit IDs used in reproducing the issue:
not important
#### Steps to reproduce the behavior:
I download MoPubUnity.unitypackage from `mopub-unity-sdk/mopub-unity-plugin` and imported in my project. Right after initialization is complete and i get OnSdkInitializedEvent callback my apk crashes with the exception. Do I miss some of the libraries? You know, I downloaded manually all those files from `$project\Assets\MoPub\Plugins\Android\MoPub.plugin\README.txt` and inserted in this directory, but it didn't work. I'm not familiar with these android things, what am i missing?

#### Evidence:
java.lang.Error: FATAL EXCEPTION [main]
Unity version : 2018.3.2f1
Device model : Xiaomi Redmi 4
Device fingerprint: Xiaomi/markw/markw:6.0.1/MMB29M/V9.5.3.0.MBEMIFA:user/release-keys

Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
at com.mopub.common.util.DeviceUtils.isPermissionGranted(DeviceUtils.java:258)
at com.mopub.mraid.MraidNativeCommandHandler.isStorePictureSupported(MraidNativeCommandHandler.java:141)
at com.mopub.mobileads.AdViewController.<init>(AdViewController.java:118)
at com.mopub.mobileads.factories.AdViewControllerFactory.internalCreate(AdViewControllerFactory.java:25)
at com.mopub.mobileads.factories.AdViewControllerFactory.create(AdViewControllerFactory.java:21)
at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:72)
at com.mopub.mobileads.MoPubView.<init>(MoPubView.java:58)
at com.mopub.mobileads.MoPubInterstitial$MoPubInterstitialView.<init>(MoPubInterstitial.java:457)
at com.mopub.mobileads.MoPubInterstitial.<init>(MoPubInterstitial.java:80)
at com.mopub.unity.MoPubInterstitialUnityPlugin$1.run(MoPubInterstitialUnityPlugin.java:53)
at com.mopub.unity.MoPubUnityPlugin$9.run(MoPubUnityPlugin.java:450)
at android.os.Handler.handleCallback(Handler.java:742)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:157)
at android.app.ActivityThread.main(ActivityThread.java:5571)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/com.kickthe.dummybuddyboss-2/base.apk"],nativeLibraryDirectories=[/data/app/com.kickthe.dummybuddyboss-2/lib/arm, /data/app/com.kickthe.dummybuddyboss-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
... 18 more
Suppressed: java.lang.ClassNotFoundException: android.support.v4.content.ContextCompat
at java.lang.Class.classForName(Native Method)
at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
... 19 more
Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

**Comment by Romaleks360** [comment]
Nevermind, I found the same closed topic https://github.com/mopub/mopub-unity-sdk/issues/26
please add all the needed libraries in the unitypackage, I spend the whole night on this

**Comment by chauduyphanvu1** [comment]
Our next Unity plugin is going to addresses issues like this by downloading all dependencies on your behalf, so there will be no need to manually add anything. Watch for the release soon!

Vu Chau
MoPub SDK Team
