### ISSUE TITLE
AdMob mediation llegalStateException: Only fullscreen activities can request orientation

### ISSUE THREAD

**Issue by vizgl** [mopub/mopub-unity-sdk#31]
Crash after rewarded ad
Mopub version is 5.5.0
Unity 2018.3.3f1
Android 8.0
This bug reproduced on the x86 Android 8 emulator
Also tested on emulator Android 7, crash is not present

Crash:
FATAL EXCEPTION: main
Process: com.mygamename.com, PID: 18284
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mygamename.com/com.google.android.gms.ads.AdActivity}: java.lang.IllegalStateException: Only fullscreen activities can request orientation
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2822)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2897)
	at android.app.ActivityThread.-wrap11(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:251)
	at android.app.ActivityThread.main(ActivityThread.java:6572)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Caused by: java.lang.IllegalStateException: Only fullscreen activities can request orientation
	at android.os.Parcel.readException(Parcel.java:1972)
	at android.os.Parcel.readException(Parcel.java:1899)
	at android.app.IActivityManager$Stub$Proxy.setRequestedOrientation(IActivityManager.java:5675)
	at android.app.Activity.setRequestedOrientation(Activity.java:5739)
	at com.google.android.gms.ads.internal.overlay.d.a(:com.google.android.gms.dynamite_adsdynamite@14799048@14.7.99 (040400-223214910):146)
	at com.google.android.gms.ads.internal.overlay.d.b(:com.google.android.gms.dynamite_adsdynamite@14799048@14.7.99 (040400-223214910):166)
	at com.google.android.gms.ads.internal.overlay.d.a(:com.google.android.gms.dynamite_adsdynamite@14799048@14.7.99 (040400-223214910):61)
	at com.google.android.gms.ads.internal.overlay.client.c.dispatchTransaction(:com.google.android.gms.dynamite_adsdynamite@14799048@14.7.99 (040400-223214910):37)
	at of.onTransact(:com.google.android.gms.dynamite_adsdynamite@14799048@14.7.99 (040400-223214910):11)
	at android.os.Binder.transact(Binder.java:604)
	at com.google.android.gms.internal.ads.zzew.zza(Unknown Source:20)
	at com.google.android.gms.internal.ads.zzaor.onCreate(Unknown Source:5)
	at com.google.android.gms.ads.AdActivity.onCreate(Unknown Source:9)
	at android.app.Activity.performCreate(Activity.java:6975)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
	at androidx.test.runner.MonitoringInstrumentation.callActivityOnCreate(MonitoringInstrumentation.java:172)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2775)

**Comment by sdolim** [comment]
There seems to be some change as of Android 8.0 that causes this issue.  

https://stackoverflow.com/questions/48072438/java-lang-illegalstateexception-only-fullscreen-opaque-activities-can-request-o?noredirect=1&lq=1

There needs to be some change in the manifest, it looks like.  We'll investigate to see if that's what it is and what the change would be.

**Comment by vizgl** [comment]
> There seems to be some change as of Android 8.0 that causes this issue.
> 
> https://stackoverflow.com/questions/48072438/java-lang-illegalstateexception-only-fullscreen-opaque-activities-can-request-o?noredirect=1&lq=1
> 
> There needs to be some change in the manifest, it looks like. We'll investigate to see if that's what it is and what the change would be.

I tried different combinations in the manifest file, but without results, only build fail errors. I think, you should add android version check in the code

**Comment by sdolim** [comment]
I found this in our manifest at Assets/MoPub/Plugins/Android/MoPub.plugin/AndroidManifest.xml:

        
        <activity android:name="com.google.android.gms.ads.AdActivity"
                  android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
                  android:theme="@android:style/Theme.Translucent"/>

The Transclucent theme mentioned there is referenced in the above stackoverflow link as a cause of the error.  It is due to a change in Android 8.0 (which is why you did not see the error in your Android 7 emulator).  

A poster at that link fixed the problem by changing the theme to a style that has  parent="@style/Theme.AppCompat.Light.NoActionBar".  

This is a bug in our manifest so we'll have to fix it, but you can do this (or something similar) as a workaround in the meantime.

**Comment by sdolim** [comment]
Here's something that might do the trick:  In Build Settings > Player Settings, find the Target API Level setting and make sure it is no higher than 27.  The default Unity setting is "Automatic (Highest Installed)" which is probably where the target SDK of 28 is coming from (this is the SDK level where the new rule appeared that is causing this issue).  

(I would say this is a workaround, but since it appears that the activity is declared Translucent even inside AdMob's own .aar manifest, it's likely the problem is not specific to Unity.)

**Comment by vizgl** [comment]
Yep, if I choose api level 27, crash not happen

**Comment by chauduyphanvu1** [comment]
> It seems manifest in the **play-services-ads-lite** has higher priority when manifest merge phase

Is there a reason you are using `play-services-ads-lite`? Does this crash still happen if you use `play-services-ads`? 

Separately, Google [said](https://groups.google.com/d/msg/google-admob-ads-sdk/wWPeVW25t5g/OM_EvAIKFwAJ) that you do not need an AdMob-specific `<activity>` declared in the Manifest. Feel free to remove this node (or change the `android:theme` to a different theme):

```
<!-- AdMob network SDK activities.  You may remove if unused. -->
<activity android:name="com.google.android.gms.ads.AdActivity"
          android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|uiMode|screenSize|smallestScreenSize"
          android:theme="@android:style/Theme.Translucent"/>
```

**Comment by chauduyphanvu1** [comment]
@vizgl - do you have any updates to our questions above or still need help with this issue? Let us know!

**Comment by vizgl** [comment]
> @vizgl - do you have any updates to our questions above or still need help with this issue? Let us know!

No, at the current moment I use adjust 27 and all works. Thanks
