### ISSUE TITLE
App Crashes re

### ISSUE THREAD

**Issue by mubshar1** [mopub/mopub-unity-sdk#45]
App Crashing every time upon clicking on Banner AD 
- 

#### Ad Unit IDs used in reproducing the issue:
9a2ee8c0fdb04655a0599e989058370c

#### Steps to reproduce the behavior:
1)-Open App
2) - Click on the banner  Ad
#### Expected behavior:
As concisely as possible, describe the expected behavior.

#### Observed behavior:
crash

#### Evidence:
Device fingerprint: motorola/harpia/harpia:6.0.1/MPIS24.241-2.50-16/16:user/release-keys
FATAL EXCEPTION: ControllerMessenger
Process: com.................game, PID: 16635
java.lang.Error: FATAL EXCEPTION [ControllerMessenger]
Unity version     : 2018.3.0f2
Device model      : motorola Moto G Play
Device fingerprint: motorola/harpia/harpia:6.0.1/MPIS24.241-2.50-16/16:user/release-keys
Caused by: java.lang.IllegalStateException: UiAutomation not connected!
	at android.app.UiAutomation.throwIfNotConnectedLocked(UiAutomation.java:971)
	at android.app.UiAutomation.getRootInActiveWindow(UiAutomation.java:414)
	at androidx.test.tools.crawler.platform.uiautomator.UiAutomatorStateExtractor.getAccessibilityHierarchy(UiAutomatorStateExtractor.java:24)
	at androidx.test.tools.crawler.platform.hybrid.HybridStateExtractor.getAccessibilityHierarchy(HybridStateExtractor.java:30)
	at androidx.test.tools.crawler.controller.remote.RemotePlatform.handleTakeScreenshot(RemotePlatform.java:51)
	at androidx.test.tools.crawler.controller.remote.RemotePlatform.access$500(RemotePlatform.java:93)
	at androidx.test.tools.crawler.controller.remote.RemotePlatform$ControllerMessageHandler.handleMessage(RemotePlatform.java:12)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by dravyan** [comment]
Hi @mubshar1,
   From the stack trace this seems to be a known bug with android test framework UiAutomator - https://github.com/googlesamples/android-testing/issues/89. Could you please refer to the [bug report ](https://github.com/googlesamples/android-testing/issues/89)thread and let us know any questions here?

Thanks,
Dravya Nataraj
MoPub SDKTeam

**Comment by rsatrasala** [comment]
Please re-open if required.
