### ISSUE TITLE
Android is throwing a pause-related exception when using Admob ads

### ISSUE THREAD

**Issue by IVeselovskyy** [mopub/mopub-unity-sdk#52]
When rewarded ads are displayed through Admob mediator on Android, it throws an exception about pause/resume not being called on the main UI thread. This doesn't seem to affect anything, but it would spam our crash reports with errors, which is less than ideal. 

- [*] I am submitting a bug report for existing functionality
- [*] I visited https://developers.mopub.com/ and found no answer
- [*] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [*] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.6
#### Device model and OS Version:
Tested on Android 6.0 and 9.0
#### Unity Version:
2017.4.16f
#### Steps to reproduce the behavior:
1. Load an Admob rewarded ad.
2. View it or simply background the app.
3. Check the logs for the error.

#### Evidence:
These are two errors we are getting:
```04-08 10:36:08.964 22757-22777/? E/Unity: AndroidJavaException: java.lang.IllegalStateException: pause must be called on the main UI thread.
    java.lang.IllegalStateException: pause must be called on the main UI thread.
        at ux.b(:com.google.android.gms.dynamite_adsdynamite@16089081@16.0.89 (100400-239467275):10)
        at com.google.android.gms.ads.internal.reward.e.h(:com.google.android.gms.dynamite_adsdynamite@16089081@16.0.89 (100400-239467275):22)
        at com.google.android.gms.ads.internal.reward.d.b(:com.google.android.gms.dynamite_adsdynamite@16089081@16.0.89 (100400-239467275):56)
        at com.google.android.gms.ads.internal.reward.client.g.a(:com.google.android.gms.dynamite_adsdynamite@16089081@16.0.89 (100400-239467275):77)
        at mx.onTransact(:com.google.android.gms.dynamite_adsdynamite@16089081@16.0.89 (100400-239467275):4)
        at android.os.Binder.transact(Binder.java:667)
        at com.google.android.gms.internal.ads.zzew.zza(Unknown Source:20)
        at com.google.android.gms.internal.ads.zzauy.zze(Unknown Source:30)
        at com.google.android.gms.internal.ads.zzavj.pause
```

```04-08 10:38:04.992 22757-22777/? E/Unity: AndroidJavaException: java.lang.IllegalStateException: resume must be called on the main UI thread.
    java.lang.IllegalStateException: resume must be called on the main UI thread.
        at ux.b(:com.google.android.gms.dynamite_adsdynamite@16089081@16.0.89 (100400-239467275):10)
        at com.google.android.gms.ads.internal.reward.e.i(:com.google.android.gms.dynamite_adsdynamite@16089081@16.0.89 (100400-239467275):29)
        at com.google.android.gms.ads.internal.reward.d.c(:com.google.android.gms.dynamite_adsdynamite@16089081@16.0.89 (100400-239467275):66)
        at com.google.android.gms.ads.internal.reward.client.g.a(:com.google.android.gms.dynamite_adsdynamite@16089081@16.0.89 (100400-239467275):67)
        at mx.onTransact(:com.google.android.gms.dynamite_adsdynamite@16089081@16.0.89 (100400-239467275):4)
        at android.os.Binder.transact(Binder.java:667)
        at com.google.android.gms.internal.ads.zzew.zza(Unknown Source:20)
        at com.google.android.gms.internal.ads.zzauy.zzf(Unknown Source:34)
        at com.google.android.gms.internal.ads.zzavj.res
```
This error seems to be coming from the `OnApplicationPaused` event. This event is running on the Unity main thread, so that's probably not the issue. 
We've tested it with the example app included in the unity plugin and it throws that exception too.

**Comment by chauduyphanvu1** [comment]
Duplicate of https://github.com/mopub/mopub-unity-mediation/issues/34. 

This issue will be gone in the next AdMob adapter release due to the removal of `onPause()` and `onResume()` in https://github.com/mopub/mopub-android-mediation/pull/155/files#diff-afe59c7d6dc997d5918029cc2365d3c8L90.

**Comment by IVeselovskyy** [comment]
Sorry, didn't notice that because they didn't mention threads. Thanks!
