### ISSUE TITLE
Moat causing a dependency error in 5.9

### ISSUE THREAD

**Issue by khambadkone** [mopub/mopub-unity-sdk#85]
One line summary of the issue here

- [ X] I am submitting a bug report for existing functionality
- [X ] I visited https://developers.mopub.com/ and found no answer
- [ X] I checked https://twittercommunity.com/c/advertiser-api/mopub to make sure that this issue has not already been filed
- [ X] I checked to make sure that this issue has not already been filed

#### MoPub SDK Version:
5.9.0 Unity SDK

#### Device model and OS Version:
OnePlus 6T , Android 9

#### Unity Version:
2018.4.7f1

#### Ad Unit IDs used in reproducing the issue:
Any

#### Steps to reproduce the behavior:
Please list all relevant steps to reproduce the observed behavior.
Add MoPub 5.9 to a project
Resolve all dependencies
Make a build
Run the app

#### Expected behavior:
App would run without an issue.

#### Observed behavior:
App crashes at start with following logs :
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
        at com.moat.analytics.mobile.iro.k.ˋॱ(:5303)
        at com.moat.analytics.mobile.iro.k.ʻ(:178)
        at com.moat.analytics.mobile.iro.k.ˏ(:144)
        at com.moat.analytics.mobile.iro.k.<init>(:81)
        at com.moat.analytics.mobile.iro.k.ˎ(:63)
        at com.moat.analytics.mobile.iro.j.ॱ(:108)
        at com.moat.analytics.mobile.iro.t$5$2.ˋ(:135)
        at com.moat.analytics.mobile.iro.t$d$2.run(:245)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
#### Evidence:
Device log files, Network log file, etc.

**Comment by khambadkone** [comment]
False alarm
